yatube/about/urls.py
from django.urls import path
from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('auth/', include('users.urls', namespace='users')),
    path('about/', include('about.urls', namespace='about')),
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('django.contrib.auth.urls')),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Post(models.Model):
    text = models.TextField(
        verbose_name='Текст поста',
        help_text='Введите текст поста'
    )
    pub_date = models.DateTimeField(
        'Дата публикации',
        auto_now_add=True
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор',
        related_name='posts'
    )
    group = models.ForeignKey(
        'Group',
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Группа',
        help_text='Выберете группу'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ['-pub_date']
        verbose_name = 'Пост'

    def __str__(self):
        return self.text[:15]


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(
        'Post',
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        related_name='comments',
        verbose_name='Комментирование поста',
        help_text='Комментирование поста'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор',
        related_name='comments'
    )
    text = models.TextField(
        verbose_name='Текст комментария',
        help_text='Введите текст комментария'
    )
    created = models.DateTimeField(
        verbose_name='Дата комментария',
        auto_now_add=True
    )

    def __str__(self):
        return self.text


class Follow(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE,
        related_name="follower",
        verbose_name="Подписчик"
    )
    author = models.ForeignKey(
        User, on_delete=models.CASCADE,
        related_name="following",
        verbose_name="Подписка"
    )

    class Meta:
        db_table = "Follow"
        constraints = [models.UniqueConstraint(fields=["user", "author"],
                                               name="unique follow")]
        verbose_name_plural = "Подписки"

yatube/posts/forms.py
from django.forms import ModelForm
from .models import Comment, Post


class PostForm(ModelForm):

    class Meta:
        model = Post
        fields = ('group', 'text', 'image')


class CommentForm(ModelForm):

    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import redirect, render, get_object_or_404

from .models import Follow, Post, Group, User
from .forms import PostForm, CommentForm


Per_Page = 10


def index(request):
    post_list = Post.objects.all()
    paginator = Paginator(post_list, Per_Page)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    template = 'posts/index.html'
    context = {
        'page_obj': page_obj,
    }
    return render(request, template, context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    page_number = request.GET.get('page')
    template = 'posts/group_list.html'
    posts = group.posts.all()[:10]
    paginator = Paginator(posts, Per_Page)
    page_obj = paginator.get_page(page_number)
    context = {
        'group': group,
        'posts': posts,
        'page_obj': page_obj,
    }
    return render(request, template, context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    post_list = author.posts.all()
    paginator = Paginator(post_list, Per_Page)
    following = Follow.objects.filter(
        user__username=request.user,
        author=author,
    )
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    template = 'posts/profile.html'
    context = {
        'author': author,
        'page_obj': page_obj,
        'posts': post_list,
        'following': following,
    }
    return render(request, template, context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    comment_form = CommentForm(request.POST or None)
    comments = post.comments.all()
    text = post.text
    title = text[:25]
    author = post.author
    group = post.group
    template = 'posts/post_detail.html'
    context = {
        'author': author,
        'title': title,
        'post': post,
        'group': group,
        'form': comment_form,
        'comments': comments,
    }
    return render(request, template, context)


@login_required
def post_create(request):
    template = 'posts/create_post.html'
    form = PostForm(request.POST or None)
    if request.method == 'POST' and form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', username=post.author)
    context = {
        'form': form
    }
    return render(request, template, context)


@login_required
def post_edit(request, post_id):
    template = 'posts/create_post.html'
    is_edit = True
    post = get_object_or_404(Post, pk=post_id)
    if request.user != post.author:
        return redirect('posts:post_detail', post_id=post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if request.method == "POST" and form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id=post_id)
    context = {
        'post': post,
        'form': form,
        'is_edit': is_edit,
    }
    return render(request, template, context)


@login_required
def add_comment(request, post_id):
    # Получите пост
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    post_list = Post.objects.filter(author__following__user=request.user)
    paginator = Paginator(post_list, Per_Page)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if request.user != author:
        Follow.objects.get_or_create(user=request.user, author=author)
    return redirect('posts:profile', username)


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    follower = Follow.objects.filter(
        user=request.user, author=author)
    follower.delete()
    return redirect('posts:profile', username)

yatube/templates/posts/includes/button_follow.html
{% if following %}
<a
  class="btn btn-lg btn-light"
  href="{% url 'posts:profile_unfollow' author.username %}" role="button"
>
  Отписаться
</a>
{% else %}
  <a
    class="btn btn-lg btn-primary"
    href="{% url 'posts:profile_follow' author.username %}" role="button"
  >
    Подписаться
  </a>
{% endif %}

yatube/templates/posts/includes/paginator.html
{# templates/posts/includes/paginator.html #}

{# Отрисовываем навигацию паджинатора только если#}
    {#все посты не помещаются на первую страницу #}
    {% if page_obj.has_other_pages %}
    <nav aria-label="Page navigation" class="my-5">
      <ul class="pagination">
        {% if page_obj.has_previous %}
          <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
              Предыдущая
            </a>
          </li>
        {% endif %}
        {% for i in page_obj.paginator.page_range %}
            {% if page_obj.number == i %}
              <li class="page-item active">
                <span class="page-link">{{ i }}</span>
              </li>
            {% else %}
              <li class="page-item">
                <a class="page-link" href="?page={{ i }}">{{ i }}</a>
              </li>
            {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">
              Следующая
            </a>
          </li>
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
              Последняя
            </a>
          </li>
        {% endif %}    
      </ul>
    </nav>
    {% endif %} 

yatube/templates/posts/includes/post_item.html
<div class="card mb-3 mt-1 shadow">
    <a href="{% url 'posts:post_detail' post.pk %}">
    {% load thumbnail %}
    {% thumbnail post.image "1200" crop="center" upscale=True as im %}
    <img class="card-img" src="{{ im.url }}" />
    {% endthumbnail %}
    </a>
    <div class="card-body">
      <p class="card-text">
        <a name="post_{{ post.id }}" href="{% url 'posts:profile' post.author %}">
          <strong class="d-block text-gray-dark">{{ post.author }}</strong>
        </a>
        {{ post.text|linebreaksbr|urlizetrunc:40 }}
      </p>
      
      {% if post.group %}
      <p>
        <a class="card-link muted" href="{% url 'posts:group_list' slug=post.group.slug %}">
          <strong class="d-block text-gray-dark">{{ post.group.title }}</strong>
        </a>
      </p>
      {% endif %}
  
      <div class="d-flex justify-content-between align-items-center">
        <div class="btn-group">
          {% if not form %}
          <a class="btn btn-outline-primary btn-sm" href="{% url 'posts:post_detail' post.pk %}">Подробнее</a>
          {% endif %}
          {% if user == post.author and form %}
              <a class="btn btn-outline-primary btn-sm" href="{% url 'posts:post_edit' post.id %}" role="button">
                Редактировать
              </a>
          {% endif %}
        </div>
        <div class="text-muted">
          <small>{{ post.pub_date }}</small>
        </div>
      </div>
    </div>
  </div>    

yatube/templates/posts/includes/profile_item.html
<aside class="col-md-3 mb-3 mt-1">
    <ul class="list-group">
      <li class="list-group-item d-flex justify-content-between align-items-center">
          <a href="{% url 'posts:profile' author %}"> {{ author.username }} </a>
      </li>
      <li class="list-group-item d-flex justify-content-between align-items-center">
          {{ author.get_full_name }} 
      </li>
      <li class="list-group-item d-flex justify-content-between align-items-center">
      <a href="{% url 'posts:profile' username=author.username %}"> Всего постов </a> 
          <span class="badge bg-primary rounded-pill"> {{ author.posts.count }} </span>
      </li>
      {% if user != author %}
        <li class="list-group-item d-flex justify-content-between align-items-center">
          {% include 'posts/includes/button_follow.html'%}
        </li>
      {% endif %}
    </ul>
</aside>

yatube/templates/posts/includes/switcher.html
{% if user.is_authenticated %}
  <div class="row my-3">
    <ul class="nav nav-tabs">
      <li class="nav-item">
        <a 
          class="nav-link {% if index %}active{% endif %}"
          href="{% url 'posts:index' %}"
        >
          Все авторы
        </a>
      </li>
      <li class="nav-item">
        <a 
           class="nav-link {% if follow %}active{% endif %}"
           href="{% url 'posts:follow_index' %}"
        >
          Избранные авторы
        </a>
      </li>
    </ul>
  </div>
{% endif %}