yatube/about/urls.py
from django.urls import path
from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('auth/', include('users.urls', namespace='users')),
    path('about/', include('about.urls', namespace='about')),
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('django.contrib.auth.urls')),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Post(models.Model):
    text = models.TextField(
        verbose_name='Текст поста',
        help_text='Введите текст поста'
    )
    pub_date = models.DateTimeField(
        'Дата публикации',
        auto_now_add=True
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор',
        related_name='posts'
    )
    group = models.ForeignKey(
        'Group',
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Группа',
        help_text='Выберете группу'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ['-pub_date']
        verbose_name = 'Пост'

    def __str__(self):
        return self.text[:15]


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(
        'Post',
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        related_name='comments',
        verbose_name='Комментирование поста',
        help_text='Комментирование поста'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор',
        related_name='comments'
    )
    text = models.TextField(
        verbose_name='Текст комментария',
        help_text='Введите текст комментария'
    )
    created = models.DateTimeField(
        verbose_name='Дата комментария',
        auto_now_add=True
    )

    def __str__(self):
        return self.text


class Follow(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE,
        related_name="follower",
        verbose_name="Подписчик"
    )
    author = models.ForeignKey(
        User, on_delete=models.CASCADE,
        related_name="following",
        verbose_name="Подписка"
    )

    class Meta:
        db_table = "Follow"
        constraints = [models.UniqueConstraint(fields=["user", "author"],
                                               name="unique follow")]
        verbose_name_plural = "Подписки"

yatube/posts/forms.py
from django.forms import ModelForm
from .models import Comment, Post


class PostForm(ModelForm):

    class Meta:
        model = Post
        fields = ('group', 'text', 'image')


class CommentForm(ModelForm):

    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import redirect, render, get_object_or_404

from .models import Follow, Post, Group, User
from .forms import PostForm, CommentForm


Per_Page = 10


def index(request):
    post_list = Post.objects.all()
    paginator = Paginator(post_list, Per_Page)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    template = 'posts/index.html'
    context = {
        'page_obj': page_obj,
    }
    return render(request, template, context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    page_number = request.GET.get('page')
    template = 'posts/group_list.html'
    posts = group.posts.all()[:10]
    paginator = Paginator(posts, Per_Page)
    page_obj = paginator.get_page(page_number)
    context = {
        'group': group,
        'posts': posts,
        'page_obj': page_obj,
    }
    return render(request, template, context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    post_list = author.posts.all()
    paginator = Paginator(post_list, Per_Page)
    following = Follow.objects.filter(
        user__username=request.user,
        author=author,
    )
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    template = 'posts/profile.html'
    context = {
        'author': author,
        'page_obj': page_obj,
        'posts': post_list,
        'following': following,
    }
    return render(request, template, context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    comment_form = CommentForm(request.POST or None)
    comments = post.comments.all()
    text = post.text
    title = text[:25]
    author = post.author
    group = post.group
    template = 'posts/post_detail.html'
    context = {
        'author': author,
        'title': title,
        'post': post,
        'group': group,
        'form': comment_form,
        'comments': comments,
    }
    return render(request, template, context)


@login_required
def post_create(request):
    template = 'posts/create_post.html'
    form = PostForm(request.POST or None)
    if request.method == 'POST' and form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', username=post.author)
    context = {
        'form': form
    }
    return render(request, template, context)


@login_required
def post_edit(request, post_id):
    template = 'posts/create_post.html'
    is_edit = True
    post = get_object_or_404(Post, pk=post_id)
    if request.user != post.author:
        return redirect('posts:post_detail', post_id=post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if request.method == "POST" and form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id=post_id)
    context = {
        'post': post,
        'form': form,
        'is_edit': is_edit,
    }
    return render(request, template, context)


@login_required
def add_comment(request, post_id):
    # Получите пост
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    post_list = Post.objects.filter(author__following__user=request.user)
    paginator = Paginator(post_list, Per_Page)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if request.user != author:
        Follow.objects.get_or_create(user=request.user, author=author)
    return redirect('posts:profile', username)


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    follower = Follow.objects.filter(
        user=request.user, author=author)
    follower.delete()
    return redirect('posts:profile', username)

yatube/templates/posts/comment.html
<!-- Форма добавления комментария -->
{% load user_filters %}

{% if user.is_authenticated %}
  <div class="card my-4">
    <h5 class="card-header">Добавить комментарий:</h5>
    <div class="card-body">
      <form method="post" action="{% url 'posts:add_comment' post.id %}">
        {% csrf_token %}      
        <div class="form-group mb-2">
          {{ form.text|addclass:"form-control" }}
        </div>
        <button type="submit" class="btn btn-primary">Отправить</button>
      </form>
    </div>
  </div>
{% endif %}

{% for comment in comments %}
  <div class="media mb-4">
    <div class="media-body">
      <h5 class="mt-0">
        <a href="{% url 'posts:profile' comment.author.username %}">
          {{ comment.author.username }}
        </a>
      </h5>
        <p>
         {{ comment.text }}
        </p>
      </div>
    </div>
{% endfor %}

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}{% if is_edit %}Редактировать пост{% else %}Новый пост{% endif %}{% endblock %}
{% load user_filters %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">{% if is_edit %}Редактировать пост{% else %}Новый пост{% endif %}</div>
        <div class="card-body">

            <form method="POST" class="post-form" enctype="multipart/form-data">
                {% csrf_token %}
                {% for field in form %}
                    <div class="form-group row my-3 p-3" aria-required={% if field.field.required %}"true"{% else %}"false"{% endif %}>
                        <label for="{{ field.id_for_label }}">
                        {{ field.label }}
                        {% if field.field.required %}<span class="required text-danger">*</span>{% endif %}</label>
                        <div class="col-md-12">

                            {{ field|addclass:"form-control" }}

                            {% if field.help_text %}
                            <small id="{{ field.id_for_label }}-help" class="form-text text-muted">{{ field.help_text|safe }}</small>
                            {% endif %}
                        </div>
                        {% if form.errors %}
                        {% for field in form %}
                          {% for error in field.errors %}            
                            <div class="alert alert-danger">
                              {{ error|escape }}
                            </div>
                          {% endfor %}
                        {% endfor %}
                        {% for error in form.non_field_errors %}
                          <div class="alert alert-danger">
                            {{ error|escape }}
                          </div>
                        {% endfor %}
                     {% endif %}                
                    </div>
                {% endfor %}
            <div class="col-md-6 offset-md-4">    
                <button type="submit" class="btn btn-primary">
                    {% if is_edit %}
                        Сохранить
                    {% else %}
                        Добавить
                    {% endif %}               
                </button> 
            </form>

        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
  </div> <!-- row -->    
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% block title %}Посты подписки{% endblock %}
{% block content %}
  {% include 'posts/includes/switcher.html' %}
  {% for post in page_obj %}  
    {% include 'posts/includes/post_item.html'%}
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %} Записи сообщества {{ group.title }} {% endblock %}
{% block content %}
    <main>
      <!-- класс py-5 создает отступы сверху и снизу блока -->
      <div class="container py-5">
        <h1>{{ group.title }}</h1>
        <p>{{ group.description }}</p>
        {% for post in posts %}
         <ul>
           <li>
            Автор: {{ post.author.get_full_name }}
           </li>
           <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
           </li>
           {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
              <img class="card-img my-2" src="{{ im.url }}">
           {% endthumbnail %}
         </ul>
            <p>{{ post.text }}</p>
            <a href="{% url 'posts:post_edit' post.pk %}">редактирование поста</a><br>    
          {% if not forloop.last %}<hr>{% endif %}
        {% endfor %}
      </div>  
    </main>
  {% include 'posts/includes/paginator.html' %}
{% endblock %} 

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %} Последние обновления на сайте {% endblock %}
{% block content %}
  
 {% include 'posts/includes/switcher.html' %}

  {% load cache %}
  {% cache 2 sidebar %}
  
    {% for post in page_obj %}
      {% include 'posts/includes/post_item.html'%}
    {% endfor %}

  {% endcache %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% block title %} Пост {{post.text|truncatechars:30}} {% endblock %}

{% block content %}   
    <main>
      <div class="row">
        {% include 'posts/includes/profile_item.html'%}
        <article class="col-12 col-md-9">
          {% include 'posts/includes/post_item.html'%}
          {% include 'posts/comment.html'%}
        </article>
      </div> 
    </main>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %} Профайл пользователя {{author.get_full_name}} {% endblock %}

{% block content %}
  <div class="row">     
    <h2>{{ author.get_full_name }} </h2>  
    {% include 'posts/includes/profile_item.html' %}
    <article class="col-12 col-md-9">
      {% for post in page_obj %}  
        {% include 'posts/includes/post_item.html'%}
        {% if not forloop.last %}<hr>{% endif %}
      {% endfor %} 
      {% include 'posts/includes/paginator.html' %} 
    </article>
  </div>
{% endblock %}